package PDF;

import com.itextpdf.kernel.colors.ColorConstants;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfReader;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.properties.TextAlignment;
import com.itextpdf.layout.properties.UnitValue;

import java.io.IOException;


public class PdfModifyBasedOnImageHc {
    public static void main(String[] args) throws IOException {
        String src = "C:\\Users\\Admin\\Documents\\Docs\\PdfGenerator.pdf";
        String dest = "C:\\Users\\Admin\\Documents\\Docs\\PdfData1.pdf";

        PdfDocument pdf = new PdfDocument(new PdfReader(src), new PdfWriter(dest));
        Document doc = new Document(pdf);

        Paragraph p = new Paragraph("Invoice No : FR-001\nDate : 16-July-2025\nSupplier : ABC Freight Ltd.\nBuyer : XYZ Pvt Ltd.");
        p.setTextAlignment(TextAlignment.LEFT);
        p.setMarginBottom(15);
        doc.add(p);

        Table table = new Table(UnitValue.createPercentArray(4)).useAllAvailableWidth();
        table.addHeaderCell(
                new Cell().add(new Paragraph("Description"))
                        .setFontColor(ColorConstants.RED)
        );
        table.addHeaderCell(
                new Cell().add(new Paragraph("Quantity"))
                        .setFontColor(ColorConstants.RED)
        );
        table.addHeaderCell(
                new Cell().add(new Paragraph("Rate"))
                        .setFontColor(ColorConstants.RED)
        );

        table.addHeaderCell(
                new Cell().add(new Paragraph("Amount"))
                        .setFontColor(ColorConstants.RED)
        );

        table.addCell("Freight Charges - Chennai");
        table.addCell("1");
        table.addCell("$5000");
        table.addCell("$5000");
        table.addCell("Handling Charges");
        table.addCell("1");
        table.addCell("$500");
        table.addCell("$500");
        table.setAutoLayout();

        doc.add(table);

        Paragraph pa = new Paragraph("Total Amount : $5500");
        pa.setTextAlignment(TextAlignment.CENTER);
        pa.setMarginTop(10);
        pa.setMarginBottom(10);
        doc.add(pa);


        Paragraph par = new Paragraph("Generated by FOB System");
        par.setTextAlignment(TextAlignment.RIGHT);
        par.setMarginTop(10);
        doc.add(par);

        doc.close();

        System.out.println("Pdf Modified and Saved at : " + dest);
    }
}


