package PDF;

import com.itextpdf.kernel.colors.ColorConstants;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfReader;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.properties.TextAlignment;
import com.itextpdf.layout.properties.UnitValue;

import java.io.IOException;
import java.sql.*;

public class PdfModifyBasedOnImage {
    public static void main(String[] args) throws IOException, SQLException {
        String src = "C:\\Users\\Admin\\Documents\\Docs\\PdfGenerator.pdf";
        String dest = "C:\\Users\\Admin\\Documents\\Docs\\PdfData2.pdf";

        PdfDocument pdf = new PdfDocument(new PdfReader(src), new PdfWriter(dest));
        Document doc = new Document(pdf);

        Paragraph p = new Paragraph("Invoice No : FR-001\nDate : 16-July-2025\nSupplier : ABC Freight Ltd.\nBuyer : XYZ Pvt Ltd.");
        p.setTextAlignment(TextAlignment.LEFT);
        p.setMarginBottom(15);
        doc.add(p);

        final String url = "jdbc:postgresql://localhost:5432/demo";
        final String user = "postgres";
        final String pass = "7059";

        String query = "SELECT \"Description\", \"Quantity\", \"Rate\", \"Amount\" FROM invoice";

        Table table = new Table(UnitValue.createPercentArray(4)).useAllAvailableWidth();
        table.addHeaderCell(
                new Cell().add(new Paragraph("Description"))
                        .setFontColor(ColorConstants.RED)
        );
        table.addHeaderCell(
                new Cell().add(new Paragraph("Quantity"))
                        .setFontColor(ColorConstants.RED)
        );
        table.addHeaderCell(
                new Cell().add(new Paragraph("Rate"))
                        .setFontColor(ColorConstants.RED)
        );

        table.addHeaderCell(
                new Cell().add(new Paragraph("Amount"))
                        .setFontColor(ColorConstants.RED)
        );

        double totalAmount = 0.0;

        Connection con = DriverManager.getConnection(url,user,pass);
        PreparedStatement ps = con.prepareStatement(query);
        ResultSet rs = ps.executeQuery();

        while(rs.next()){
            String description = rs.getString("Description");
            int quantity = rs.getInt("Quantity");
            int rate = (int) rs.getDouble("Rate");
            int amount = (int) rs.getDouble("Amount");

            table.addCell(description);
            table.addCell(String.valueOf(quantity));
            table.addCell(String.valueOf(rate));
            table.addCell(String.valueOf(amount));

            table.setAutoLayout();

            totalAmount += amount;

        }
        doc.add(table);

        Paragraph pa = new Paragraph("Total Amount : " + totalAmount);
        pa.setTextAlignment(TextAlignment.CENTER);
        pa.setMarginTop(10);
        pa.setMarginBottom(10);
        doc.add(pa);


        Paragraph par = new Paragraph("Generated by FOB System");
        par.setTextAlignment(TextAlignment.RIGHT);
        par.setMarginTop(10);
        doc.add(par);

        doc.close();

        System.out.println("Pdf Modified and Saved at : " + dest);
    }

}
